/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder2_14 (
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] s,
    output reg [0:0] z,
    output reg [0:0] v,
    output reg [0:0] n
  );
  
  
  
  reg [15:0] s_out;
  
  always @* begin
    s_out = 16'h0000;
    
    case (alufn[0+0-:1])
      1'h0: begin
        s_out = a + b;
      end
      1'h1: begin
        s_out = a - b;
      end
      default: begin
        s_out = 16'h0000;
      end
    endcase
    n = s_out[15+0-:1];
    v = (a[15+0-:1] & (b[15+0-:1] ^ alufn[0+0-:1]) & !s_out[15+0-:1]) | (!a[15+0-:1] & !(b[15+0-:1] ^ alufn[0+0-:1]) & s_out[15+0-:1]);
    z = ~(|s_out);
    s = s_out;
  end
endmodule
