/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module sixteen_bit_2s_complement_20 (
    input [15:0] a,
    output reg [15:0] n
  );
  
  
  
  always @* begin
    n = ~a + 1'h1;
  end
endmodule
